let box1 = document.getElementById('box1').style
let box2 = document.getElementById('box2').style
let box3 = document.getElementById('box3').style
let box4 = document.getElementById('box4').style
let box5 = document.getElementById('box5').style
box1.color = 'red';box1.backgroundColor= 'green'
box2.color = 'aqua';box2.backgroundColor= 'red'
box3.color = 'white';box3.backgroundColor= 'orange'
box4.color = 'blue';box4.backgroundColor= 'white'
box5.color = 'orange';box5.backgroundColor= 'blue'
